### ISSUE TITLE
docker运行报错

### ISSUE THREAD

**Issue by kozora** [DIYgod/Weibo2RSS#3]
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/index.js:9:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
error: Forever detected script exited with code: 1
error: Script restart attempt #23
/usr/src/app/routes/negative.js:65
            for (let i = 0; i < wbs.length; i++) {
                 ^^^
```

**Comment by DIYgod** [comment]
直接 `node index.js` 就行了，docker 坏掉了

**Comment by kozora** [comment]
直接`node index.js` 后网页报错Cannot GET /weibo/rss/

**Comment by kozora** [comment]
![QQ截图20171017013349.png](https://i.loli.net/2017/10/17/59e4edc010021.png)

![QQ截图20171017013534.png](https://i.loli.net/2017/10/17/59e4edee579ba.png)

**Comment by DIYgod** [comment]
http://127.0.0.1:1206/rss/3306934123
